// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import ClientWrapper from "./components/ClientWrapper";
// import WhatsAppButton from "@/app/components/WhatsAppButton";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Stowave",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
      // <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <ClientWrapper>
//           {children}
//         </ClientWrapper>
//         <WhatsAppButton />
        
//       </body>
//     </html>
//   );
// }
// // https://business.facebook.com/latest/settings/events_dataset_and_pixel?business_id=636026412913261





import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./components/ClientWrapper";
import WhatsAppButton from "@/app/components/WhatsAppButton";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Stowave",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Meta Pixel Code */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '907344864993941');
              fbq('track', 'PageView');
            `,
          }}
        />
        <noscript>
          <img height="1" width="1" style={{display:"none"}}
            src="https://www.facebook.com/tr?id=907344864993941&ev=PageView&noscript=1"
          />
        </noscript>
        {/* End Meta Pixel Code */}

        <ClientWrapper>
          {children}
        </ClientWrapper>
        <WhatsAppButton />
      </body>
    </html>
  );
}
