// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import ClientWrapper from "./components/ClientWrapper";
// import WhatsAppButton from "@/app/components/WhatsAppButton"; // correct path
// // import DragonFollower from "./components/DragonFollower";
// import BackgroundSparks from "./components/DragonCursor";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Stowave",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

//         <ClientWrapper>{children}</ClientWrapper>
//        <WhatsAppButton />
//       </body>
//     </html>
//   );
// }







// // app/layout.js
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import ClientWrapper from "./components/ClientWrapper";
// import WhatsAppButton from "@/app/components/WhatsAppButton";
// import DragonFollower from "./components/DragonFollower"; // New follower component

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Stowave",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <ClientWrapper>
//           {children}
//           {/* Dragon Follower - Original cursor ke saath */}
//           <DragonFollower />
//         </ClientWrapper>
//         <WhatsAppButton />
//       </body>
//     </html>
//   );
// }











// // app/layout.js (Final version)
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import ClientWrapper from "./components/ClientWrapper";
// import WhatsAppButton from "@/app/components/WhatsAppButton";
// import DragonFollower from "./components/MagicSparkleFollower";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Stowave",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <ClientWrapper>
//           {children}
//           {/* Dragon follower - original cursor intact rehta hai */}
//           <DragonFollower />
//         </ClientWrapper>
//         <WhatsAppButton />
//       </body>
//     </html>
//   );
// }












// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./components/ClientWrapper";
import WhatsAppButton from "@/app/components/WhatsAppButton";
import SimpleFollower from "./components/SimpleFollower"; // Choose any one
import EmojiFollower from "./components/EmojiFollower";
import MagicSparkleFollower from "./components/MagicSparkleFollower";
import CircleTrailFollower from "./components/CircleTrailFollower";
import ParticleFollower from "./components/ParticleFollower";
import MagneticBallFollower from "./components/RippleFollower";
import RippleFollower from "./components/RippleFollower";
import TextFollower from "./components/TextFollower";
import GlowOrbFollower from "./components/GlowOrbFollower";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Stowave",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientWrapper>
          {children}
          {/* Choose any follower component */}
          <ParticleFollower/>
          {/* <RippleFollower/> */}
          {/* <GlowOrbFollower/> */}
        
        </ClientWrapper>
        <WhatsAppButton />
        
      </body>
    </html>
  );
}